baseURL = "https://blog.masutech.work/"
languageCode = "ja"
title = "ますぐれメモ"
theme = "hugo-theme-cactus-plus"

[taxonomies]
  tag = "tags"
[params]
  mathjaxStyle = "mathjax-style.css"
  twitterID = "@masutech16"
  description = "個人的に気になったことや思いついたことを書き留めておくブログです"
  images = ["twitter-card.png"]
